language: csharp
sudo: required
dist: trusty
before_script:
 - chmod +x build.sh
addons:
  apt:
    packages:
    - libunwind8
before_install:
  - if test "$TRAVIS_OS_NAME" == "osx"; then brew update; brew install openssl; brew link --force openssl; fi
mono:
  - 4.0.5
os:
  - linux
  - osx
osx_image: xcode7.1
branches:
  only:
    - master
    - release
    - develop
    - /^(.*\/)?ci-.*$/
script:
  - ./build.sh verify