language: csharp
sudo: required
dist: trusty
before_script:
 - chmod +x build.sh
addons:
  apt:
    packages:
    - gettext
    - libcurl4-openssl-dev
    - libicu-dev
    - libssl-dev
    - libunwind8
    - zlib1g
before_install:
  - if test "$TRAVIS_OS_NAME" == "osx"; then brew update; brew install icu4c; fi
env:
  - KOREBUILD_TEST_DNXCORE=true
mono:
  - 4.0.5
os:
  - linux
  - osx
osx_image: xcode7.1
branches:
  only:
    - master
    - release
    - develop
    - /^(.*\/)?ci-.*$/
script:
  - ./build.sh verify