language: csharp
sudo: required
dist: trusty
before_script:
 - chmod +x build.sh
os:
  - linux
# - osx CoreCLR does not support OS X 10.9 (yet)
addons:
  apt:
    packages:
    - zsh
script:
  - ./build.sh --quiet verify