language: csharp
os:
  - osx
  - linux
sudo: required
dist: trusty
before_script:
 - chmod +x build.sh
addons:
  apt:
    packages: 
    - gettext
    - libcurl4-openssl-dev
    - libicu-dev
    - libssl-dev
    - libunwind8
branches:
  only:
    - master
    - release
    - develop
    - /^(.*\/)?ci-.*$/
osx_image: xcode7.1
env:
  global:
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
    - DOTNET_CLI_TELEMETRY_OPTOUT: 1
before_install:  
  - if test "$TRAVIS_OS_NAME" == "osx"; then brew update; brew install openssl; ln -s /usr/local/opt/openssl/lib/libcrypto.1.0.0.dylib /usr/local/lib/; ln -s /usr/local/opt/openssl/lib/libssl.1.0.0.dylib /usr/local/lib/; fi
mono:  
  - 4.6.0
script:
  - ./build.sh
cache:
  directories:
    - src/packages
    - tools