language: csharp
sudo: required
dist: trusty
before_script:
 - chmod +x build.sh
os:
  - linux
# - osx CoreCLR does not support OS X 10.9 (yet)
addons:
  apt:
    packages:
    - gettext
    - libcurl4-openssl-dev
    - libicu-dev
    - libssl-dev
    - libunwind8
    - zlib1g
env:
  - KOREBUILD_DNU_RESTORE_CORECLR=true
mono:
  - 4.0.5
script:
  - ./build.sh --quiet verify