version: 1.0.{build}
os: Visual Studio 2017 RC
init:
  - git config --global core.autocrlf true
branches:
  only:
    - master
    - release
    - develop
    - /^(.*\/)?ci-.*$/
build_script:
  - ps: .\build.ps1
clone_depth: 1
test: off
deploy: off
environment:
  global:
    DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
    DOTNET_CLI_TELEMETRY_OPTOUT: 1